name: Eslint

on:
  pull_request:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: npx eslint src rollup.config.js
